(() => {
  'use strict';
  const homes = [
    { id: 'lunar', name: 'Lunar Oasis Villa', location: 'Sedona, Arizona', region: 'Arizona', type: 'villa', price: 300000, rent: 3000, beds: 3, baths: 2, area: 695, image: 'villa.webp', description: 'Fluid architecture, panoramic windows and golden interiors. A sculptural residence designed around a quieter rhythm of living.' },
    { id: 'cedar', name: 'Cedar Lake House', location: 'Aspen, Colorado', region: 'Colorado', type: 'house', price: 485000, rent: 5000, beds: 4, baths: 3, area: 420, image: 'forest.webp', description: 'A calm lakeside retreat surrounded by pine trees. Natural materials, warm spaces and generous windows draw the landscape indoors.' },
    { id: 'sol', name: 'Sol Residence', location: 'Palm Springs, California', region: 'California', type: 'loft', price: 625000, rent: 6500, beds: 2, baths: 2, area: 285, image: 'interior.webp', description: 'Soft curves and warm stone, with space for slow mornings. An open, light-filled residence with considered details throughout.' }
  ];
  const money = value => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(value);
  const dialog = document.querySelector('#modal');
  const contents = document.querySelector('#modal-content');
  const storage = { get(key, fallback) { try { return JSON.parse(localStorage.getItem(key)) ?? fallback; } catch { return fallback; } }, set(key, value) { try { localStorage.setItem(key, JSON.stringify(value)); } catch {} } };
  const saved = new Set(storage.get('orizon-saved', []));
  if (storage.get('saved-villa', false)) saved.add('lunar');
  function announce(message) { const el = document.querySelector('#toast'); el.textContent = message; el.classList.add('visible'); clearTimeout(window.orizonToast); window.orizonToast = setTimeout(() => el.classList.remove('visible'), 2800); }
  function scrollToSection(target) { const element = typeof target === 'string' ? document.querySelector(target) : target; if (!element) return; if (window.orizonLenis) window.orizonLenis.scrollTo(element, { offset: -95 }); else element.scrollIntoView({ behavior: window.matchMedia('(prefers-reduced-motion: reduce)').matches ? 'auto' : 'smooth', block: 'start' }); }
  function updateSaveButtons() { document.querySelectorAll('[data-save]').forEach(button => { const on = saved.has(button.dataset.save); button.setAttribute('aria-pressed', String(on)); button.textContent = button.classList.contains('save-home') ? (on ? '♥' : '♡') : (on ? 'Saved to collection' : 'Save this home'); }); const heroSave = document.querySelector('[data-action="save"]'); heroSave.setAttribute('aria-pressed', String(saved.has('lunar'))); document.querySelector('#save-count').textContent = saved.has('lunar') ? '158' : '157'; }
  function toggleSaved(id) { if (saved.has(id)) saved.delete(id); else saved.add(id); storage.set('orizon-saved', [...saved]); storage.set('saved-villa', saved.has('lunar')); updateSaveButtons(); announce(saved.has(id) ? 'Home saved to your collection' : 'Home removed from your collection'); }
  function openHome(id) { const home = homes.find(item => item.id === id); if (!home) return; contents.innerHTML = `<article class="modal-home"><span class="modal-location">${home.location.toUpperCase()}</span><h2>${home.name}</h2><img src="${home.image}" alt="${home.name}"><p>${home.description}</p><div class="modal-specs"><span>${home.beds} bedrooms</span><span>${home.baths} bathrooms</span><span>${home.area} m²</span></div><div class="modal-bottom"><strong>${money(home.price)}</strong><button class="pill dark" data-save="${home.id}">Save this home</button></div></article>`; updateSaveButtons(); if (!dialog.open) dialog.showModal(); }
  function showSaved() { const selected = homes.filter(home => saved.has(home.id)); contents.innerHTML = `<div class="saved-list"><h2>Your saved homes</h2>${selected.length ? selected.map(home => `<button data-home="${home.id}">${home.name} · ${money(home.price)}</button>`).join('') : '<p>Your collection is waiting. Tap the heart on a home to save it here.</p><button id="browse-saved-empty">Explore the collection</button>'}</div>`; if (!dialog.open) dialog.showModal(); }
  document.addEventListener('click', event => { const save = event.target.closest('[data-save]'); if (save) { toggleSaved(save.dataset.save); return; } const home = event.target.closest('[data-home]'); if (home) { openHome(home.dataset.home); return; } if (event.target.closest('#browse-saved-empty')) { dialog.close(); scrollToSection('#collection'); } const link = event.target.closest('a[href^="#"]'); if (link) { const target = document.querySelector(link.getAttribute('href')); if (target) { event.preventDefault(); scrollToSection(target); } } });
  document.querySelector('.back-top').onclick = () => scrollToSection('#top');
  document.querySelector('#view-saved').onclick = showSaved;
  document.querySelectorAll('[data-action="profile"]').forEach(b => b.onclick = showSaved);
  document.querySelectorAll('[data-action="properties"]').forEach(b => b.onclick = () => scrollToSection('#collection'));
  document.querySelectorAll('[data-action="details"]').forEach(b => b.onclick = () => openHome('lunar'));
  document.querySelectorAll('[data-action="contact"]').forEach(b => b.onclick = () => scrollToSection('#shortlist'));
  document.querySelector('[data-action="save"]').onclick = () => toggleSaved('lunar');
  document.querySelector('[data-action="home"]').onclick = () => scrollToSection('#top');
  function filterHomes(predicate, message, type = 'all') { document.querySelectorAll('.residence').forEach(card => { card.hidden = !predicate(homes.find(h => h.id === card.dataset.id)); }); const count = document.querySelectorAll('.residence:not([hidden])').length; document.querySelector('#empty-properties').hidden = count > 0; document.querySelector('.property-stack').hidden = !count; document.querySelector('#filter-summary').textContent = `${count} ${count === 1 ? 'residence' : 'residences'} · ${message}`; document.querySelectorAll('[data-filter]').forEach(button => { const active = button.dataset.filter === type; button.classList.toggle('is-active', active); button.setAttribute('aria-pressed', String(active)); }); window.dispatchEvent(new CustomEvent('orizon:layout')); }
  function resetFilters() { filterHomes(() => true, 'Explore the full collection.'); }
  document.querySelectorAll('[data-filter]').forEach(button => button.onclick = () => { const type = button.dataset.filter; filterHomes(home => type === 'all' || home.type === type, type === 'all' ? 'Explore the full collection.' : `Selected ${button.textContent.toLowerCase()}.`, type); });
  document.querySelector('#reset-filter').onclick = resetFilters;
  function applyHeroFilters() { const region = document.querySelector('[aria-label="Location"]').value; const type = document.querySelector('[aria-label="Property type"]').value.toLowerCase(); const budget = Number(document.querySelector('[aria-label="Maximum price"]').value.replace(/[^0-9]/g, '')); const rent = document.querySelector('[data-mode="rent"]').classList.contains('active'); filterHomes(home => home.region === region && home.type === type && (rent ? home.rent : home.price) <= budget, `${region} · ${type} · up to ${money(budget)}${rent ? '/month' : ''}`, type); }
  document.querySelectorAll('.filters select').forEach(select => select.addEventListener('change', applyHeroFilters));
  document.querySelectorAll('[data-mode]').forEach(button => button.addEventListener('click', applyHeroFilters));
  document.querySelector('[data-action="search"]').onclick = () => { applyHeroFilters(); scrollToSection('#collection'); };
  const budget = document.querySelector('#budget'); budget.oninput = () => document.querySelector('#budget-output').textContent = money(Number(budget.value));
  document.querySelector('#shortlist-form').addEventListener('submit', event => { event.preventDefault(); const selected = new FormData(event.currentTarget).get('setting'); const matches = homes.filter(home => (selected === 'all' || home.id === selected) && home.price <= Number(budget.value)); document.querySelector('#shortlist-result').innerHTML = matches.length ? `<strong>${matches.length === 1 ? 'Your starting point' : 'Your shortlist'}</strong>${matches.map(home => `<button data-home="${home.id}">${home.name} · ${money(home.price)}</button>`).join('')}` : '<strong>A little more room to explore.</strong><p>No residence matches this setting and budget yet. Increase your budget or choose “I’m open to inspiration”.</p>'; window.ScrollTrigger?.refresh(); });
  document.querySelectorAll('.journey-steps details').forEach(detail => detail.addEventListener('toggle', () => { if (detail.open) document.querySelectorAll('.journey-steps details').forEach(other => { if (other !== detail) other.open = false; }); window.ScrollTrigger?.refresh(); }));
  document.querySelector('#year').textContent = new Date().getFullYear();
  updateSaveButtons();
  window.orizon = { homes, scrollToSection, filterHomes, resetFilters };
})();
